# DataFrame Creation

In [5]:
import pandas

In [6]:
d1={'name':['smith','blake','clark','smith','miller'],
    'sal':[2000,3000,1000,2000,1000],
    'comm':[None,None,100,None,500],
    'deptno':[10.0,20.0,10.0,10.0,30.0],
    'hiredate':['12/dec/2000','1/dec/2000','10/aug/2000','12/dec/2000','12/jan/2001'],
    }

no_of_keys==>no_of_cols
no_of_list_eles==>no_of_rows

In [7]:
df1=pandas.DataFrame(d1)

In [8]:
df1

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2000
4  miller  1000  500.0    30.0  12/jan/2001

# Series caretion

In [9]:
import pandas

In [10]:
l=['red', 'green' , 'blue', 'green', 'violet']
s=pandas.Series(l,name='colours')

In [11]:
s

0       red
1     green
2      blue
3     green
4    violet
Name: colours, dtype: object

In [12]:
s[2]

'blue'

In [13]:
#we can update the values
s[0]='brown'
s

0     brown
1     green
2      blue
3     green
4    violet
Name: colours, dtype: object

In [14]:
#inserting new values
s[5]='orange'
s

0     brown
1     green
2      blue
3     green
4    violet
5    orange
Name: colours, dtype: object

In [15]:
s.drop(index=4)

0     brown
1     green
2      blue
3     green
5    orange
Name: colours, dtype: object

In [16]:
s

0     brown
1     green
2      blue
3     green
4    violet
5    orange
Name: colours, dtype: object

In [17]:
s=s.drop(index=4)

In [18]:
s

0     brown
1     green
2      blue
3     green
5    orange
Name: colours, dtype: object

In [19]:
l1=[10,20,100.7]
pandas.Series(l1)

0     10.0
1     20.0
2    100.7
dtype: float64

In [20]:
s[::2]

0     brown
2      blue
5    orange
Name: colours, dtype: object

In [21]:
s[:3:1]

0    brown
1    green
2     blue
Name: colours, dtype: object

In [22]:
d2={'name':['scott','martin','adams','martin','miller'],
    'sal':[3000,7000,1000,6000,5000],
    'comm':[None,None,100,None,500],
    'deptno':[10.0,30.0,30.0,20.0,30.0],
    'hiredate':['12/apr/2000','1/may/2000','10/aug/2000','12/dec/2000','12/jan/2002'],
    }

df2=pandas.DataFrame(d2)

In [23]:
df2

     name   sal   comm  deptno     hiredate
0   scott  3000    NaN    10.0  12/apr/2000
1  martin  7000    NaN    30.0   1/may/2000
2   adams  1000  100.0    30.0  10/aug/2000
3  martin  6000    NaN    20.0  12/dec/2000
4  miller  5000  500.0    30.0  12/jan/2002

## concat()

In [24]:
#by default axis=0(joins the data row by row)
df=pandas.concat([df1,df2], axis=0)
df

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2000
4  miller  1000  500.0    30.0  12/jan/2001
0   scott  3000    NaN    10.0  12/apr/2000
1  martin  7000    NaN    30.0   1/may/2000
2   adams  1000  100.0    30.0  10/aug/2000
3  martin  6000    NaN    20.0  12/dec/2000
4  miller  5000  500.0    30.0  12/jan/2002

In [25]:
df=df.reset_index(drop=True) #to reset all the index and to drop the previous index use Drop=True reset_index()
df

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2000
4  miller  1000  500.0    30.0  12/jan/2001
5   scott  3000    NaN    10.0  12/apr/2000
6  martin  7000    NaN    30.0   1/may/2000
7   adams  1000  100.0    30.0  10/aug/2000
8  martin  6000    NaN    20.0  12/dec/2000
9  miller  5000  500.0    30.0  12/jan/2002

In [26]:
df3=pandas.DataFrame({'column_x':[0]*10,
                      'column_y':[None]*10})
df3

   column_x column_y
0         0     None
1         0     None
2         0     None
3         0     None
4         0     None
5         0     None
6         0     None
7         0     None
8         0     None
9         0     None

In [27]:
df=pandas.concat([df,df3],axis=1)

In [28]:
df

     name   sal   comm  deptno     hiredate  column_x column_y
0   smith  2000    NaN    10.0  12/dec/2000         0     None
1   blake  3000    NaN    20.0   1/dec/2000         0     None
2   clark  1000  100.0    10.0  10/aug/2000         0     None
3   smith  2000    NaN    10.0  12/dec/2000         0     None
4  miller  1000  500.0    30.0  12/jan/2001         0     None
5   scott  3000    NaN    10.0  12/apr/2000         0     None
6  martin  7000    NaN    30.0   1/may/2000         0     None
7   adams  1000  100.0    30.0  10/aug/2000         0     None
8  martin  6000    NaN    20.0  12/dec/2000         0     None
9  miller  5000  500.0    30.0  12/jan/2002         0     None

## head()

In [29]:
df.head() #by default argument n=5

     name   sal   comm  deptno     hiredate  column_x column_y
0   smith  2000    NaN    10.0  12/dec/2000         0     None
1   blake  3000    NaN    20.0   1/dec/2000         0     None
2   clark  1000  100.0    10.0  10/aug/2000         0     None
3   smith  2000    NaN    10.0  12/dec/2000         0     None
4  miller  1000  500.0    30.0  12/jan/2001         0     None

In [30]:
df.head(3) #n can be positional or keyword

    name   sal   comm  deptno     hiredate  column_x column_y
0  smith  2000    NaN    10.0  12/dec/2000         0     None
1  blake  3000    NaN    20.0   1/dec/2000         0     None
2  clark  1000  100.0    10.0  10/aug/2000         0     None

## tail()

In [31]:
df.tail()

     name   sal   comm  deptno     hiredate  column_x column_y
5   scott  3000    NaN    10.0  12/apr/2000         0     None
6  martin  7000    NaN    30.0   1/may/2000         0     None
7   adams  1000  100.0    30.0  10/aug/2000         0     None
8  martin  6000    NaN    20.0  12/dec/2000         0     None
9  miller  5000  500.0    30.0  12/jan/2002         0     None

In [32]:
df.tail(n=3)

     name   sal   comm  deptno     hiredate  column_x column_y
7   adams  1000  100.0    30.0  10/aug/2000         0     None
8  martin  6000    NaN    20.0  12/dec/2000         0     None
9  miller  5000  500.0    30.0  12/jan/2002         0     None

In [33]:
df.tail(3)

     name   sal   comm  deptno     hiredate  column_x column_y
7   adams  1000  100.0    30.0  10/aug/2000         0     None
8  martin  6000    NaN    20.0  12/dec/2000         0     None
9  miller  5000  500.0    30.0  12/jan/2002         0     None