# Movies Data
***Pandas***

In [209]:
import pandas as pd

In [210]:
d={
    'Movie' : ['toxic','durandhar','avengers: Endgame','Jawan','alavaikuntapuram','Marvel: deadpool', 'Bahubali','spider-Man No way home','K.g.F: 2','marvel: Doctor strange'],
    'Rating' : [9.5,9.5,10,8,None,9,9,10,10,None],
    'Language-year' : ['kannada-2026','hindi-2025','english-2019','hindi-2024','telugu-2020','english-2016','tElugu-2018','english-2024','KAnnada-2020','EnGlish-2022'],
    'Cast' : [['Yash','Kiara Advani'],['Ranbeer Singh','Sara'],['RDJ','Scarlett Johnson','Steve Rogers'],['Sharukhan','Deepika Padukone'],['Allu Arjun','Pooja Hegde'],['Wade Wilson','Juli'],['Prabhas','Tamanna'],['Tom Holland','Zendaya'],['Yash','Srinidhi Shetty'],['Benedict Cumberbatch','Cristine']],
    'Hotstar' : [0,1,1,0,0,1,0,0,0,1],
    'Netflix' : ['no','yes','no','yes','yes','no','yes','yes','yes','no']
}

In [211]:
d

{'Movie': ['toxic',
  'durandhar',
  'avengers: Endgame',
  'Jawan',
  'alavaikuntapuram',
  'Marvel: deadpool',
  'Bahubali',
  'spider-Man No way home',
  'K.g.F: 2',
  'marvel: Doctor strange'],
 'Rating': [9.5, 9.5, 10, 8, None, 9, 9, 10, 10, None],
 'Language-year': ['kannada-2026',
  'hindi-2025',
  'english-2019',
  'hindi-2024',
  'telugu-2020',
  'english-2016',
  'tElugu-2018',
  'english-2024',
  'KAnnada-2020',
  'EnGlish-2022'],
 'Cast': [['Yash', 'Kiara Advani'],
  ['Ranbeer Singh', 'Sara'],
  ['RDJ', 'Scarlett Johnson', 'Steve Rogers'],
  ['Sharukhan', 'Deepika Padukone'],
  ['Allu Arjun', 'Pooja Hegde'],
  ['Wade Wilson', 'Juli'],
  ['Prabhas', 'Tamanna'],
  ['Tom Holland', 'Zendaya'],
  ['Yash', 'Srinidhi Shetty'],
  ['Benedict Cumberbatch', 'Cristine']],
 'Hotstar': [0, 1, 1, 0, 0, 1, 0, 0, 0, 1],
 'Netflix': ['no', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no']}

## Note
- columns -> Series  
- table -> DataFrame - Converts the raw data in to the structured table format.

In [212]:
df=pd.DataFrame(d)

In [213]:
df

,Movie,Rating,Language-year,Cast,Hotstar,Netflix
0,toxic,9.5,kannada-2026,"[Yash, Kiara Advani]",0,no
1,durandhar,9.5,hindi-2025,"[Ranbeer Singh, Sara]",1,yes
2,avengers: Endgame,10.0,english-2019,"[RDJ, Scarlett Johnson, Steve Rogers]",1,no
3,Jawan,8.0,hindi-2024,"[Sharukhan, Deepika Padukone]",0,yes
4,alavaikuntapuram,NaN,telugu-2020,"[Allu Arjun, Pooja Hegde]",0,yes
5,Marvel: deadpool,9.0,english-2016,"[Wade Wilson, Juli]",1,no
6,Bahubali,9.0,tElugu-2018,"[Prabhas, Tamanna]",0,yes
7,spider-Man No way home,10.0,english-2024,"[Tom Holland, Zendaya]",0,yes
8,K.g.F: 2,10.0,KAnnada-2020,"[Yash, Srinidhi Shetty]",0,yes
9,marvel: Doctor strange,NaN,EnGlish-2022,"[Benedict Cumberbatch, Cristine]",1,no

## head( )

- head( ) method returns first half records from top of DataFrame

In [214]:
df.head()

,Movie,Rating,Language-year,Cast,Hotstar,Netflix
0,toxic,9.5,kannada-2026,"[Yash, Kiara Advani]",0,no
1,durandhar,9.5,hindi-2025,"[Ranbeer Singh, Sara]",1,yes
2,avengers: Endgame,10.0,english-2019,"[RDJ, Scarlett Johnson, Steve Rogers]",1,no
3,Jawan,8.0,hindi-2024,"[Sharukhan, Deepika Padukone]",0,yes
4,alavaikuntapuram,NaN,telugu-2020,"[Allu Arjun, Pooja Hegde]",0,yes

## tail( )

- tail( ) method returns second half records from bottom of DataFrame

In [215]:
df.tail()

,Movie,Rating,Language-year,Cast,Hotstar,Netflix
5,Marvel: deadpool,9.0,english-2016,"[Wade Wilson, Juli]",1,no
6,Bahubali,9.0,tElugu-2018,"[Prabhas, Tamanna]",0,yes
7,spider-Man No way home,10.0,english-2024,"[Tom Holland, Zendaya]",0,yes
8,K.g.F: 2,10.0,KAnnada-2020,"[Yash, Srinidhi Shetty]",0,yes
9,marvel: Doctor strange,NaN,EnGlish-2022,"[Benedict Cumberbatch, Cristine]",1,no

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Movie          10 non-null     object
 1   Rating         8 non-null      float64
 2   Language-year  10 non-null     object
 3   Cast           10 non-null     object
 4   Hotstar        10 non-null     int64
 5   Netflix        10 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 608.0+ bytes

- to access the columns of the DataFrame seperately the syntax is

- "DataFrame_name[column_name]"

In [217]:
df['Movie']

0                     toxic
1                 durandhar
2         avengers: Endgame
3                     Jawan
4          alavaikuntapuram
5          Marvel: deadpool
6                  Bahubali
7    spider-Man No way home
8                  K.g.F: 2
9    marvel: Doctor strange
Name: Movie, dtype: object

- to access multiple columns we have to enclose the names in square brackets

In [218]:
df[['Movie','Rating']]

                    Movie  Rating
0                   toxic     9.5
1               durandhar     9.5
2       avengers: Endgame    10.0
3                   Jawan     8.0
4        alavaikuntapuram     NaN
5        Marvel: deadpool     9.0
6                Bahubali     9.0
7  spider-Man No way home    10.0
8                K.g.F: 2    10.0
9  marvel: Doctor strange     NaN

In [219]:
df[df['Movie']=='K.g.F: 2']

      Movie  Rating Language-year                     Cast  Hotstar Netflix
8  K.g.F: 2    10.0  KAnnada-2020  [Yash, Srinidhi Shetty]        0     yes

In [220]:
df[df['Movie']=='toxic']

   Movie  Rating Language-year                  Cast  Hotstar Netflix
0  toxic     9.5  kannada-2026  [Yash, Kiara Advani]        0      no

In [221]:
df['Movies']=df['Movie'].str.title()

In [222]:
df

,Movie,Rating,Language-year,Cast,Hotstar,Netflix,Movies
0,toxic,9.5,kannada-2026,"[Yash, Kiara Advani]",0,no,Toxic
1,durandhar,9.5,hindi-2025,"[Ranbeer Singh, Sara]",1,yes,Durandhar
2,avengers: Endgame,10.0,english-2019,"[RDJ, Scarlett Johnson, Steve Rogers]",1,no,Avengers: Endgame
3,Jawan,8.0,hindi-2024,"[Sharukhan, Deepika Padukone]",0,yes,Jawan
4,alavaikuntapuram,NaN,telugu-2020,"[Allu Arjun, Pooja Hegde]",0,yes,Alavaikuntapuram
5,Marvel: deadpool,9.0,english-2016,"[Wade Wilson, Juli]",1,no,Marvel: Deadpool
6,Bahubali,9.0,tElugu-2018,"[Prabhas, Tamanna]",0,yes,Bahubali
7,spider-Man No way home,10.0,english-2024,"[Tom Holland, Zendaya]",0,yes,Spider-Man No Way Home
8,K.g.F: 2,10.0,KAnnada-2020,"[Yash, Srinidhi Shetty]",0,yes,K.G.F: 2
9,marvel: Doctor strange,NaN,EnGlish-2022,"[Benedict Cumberbatch, Cristine]",1,no,Marvel: Doctor Strange

In [223]:
df=df.drop(columns=['Movie'])

In [224]:
df

,Rating,Language-year,Cast,Hotstar,Netflix,Movies
0,9.5,kannada-2026,"[Yash, Kiara Advani]",0,no,Toxic
1,9.5,hindi-2025,"[Ranbeer Singh, Sara]",1,yes,Durandhar
2,10.0,english-2019,"[RDJ, Scarlett Johnson, Steve Rogers]",1,no,Avengers: Endgame
3,8.0,hindi-2024,"[Sharukhan, Deepika Padukone]",0,yes,Jawan
4,NaN,telugu-2020,"[Allu Arjun, Pooja Hegde]",0,yes,Alavaikuntapuram
5,9.0,english-2016,"[Wade Wilson, Juli]",1,no,Marvel: Deadpool
6,9.0,tElugu-2018,"[Prabhas, Tamanna]",0,yes,Bahubali
7,10.0,english-2024,"[Tom Holland, Zendaya]",0,yes,Spider-Man No Way Home
8,10.0,KAnnada-2020,"[Yash, Srinidhi Shetty]",0,yes,K.G.F: 2
9,NaN,EnGlish-2022,"[Benedict Cumberbatch, Cristine]",1,no,Marvel: Doctor Strange

In [225]:
df=df.replace({'yes':1,'no':0})

C:\Users\91789\AppData\Local\Temp\ipykernel_34328\1933910913.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace({'yes':1,'no':0})

In [226]:
df

,Rating,Language-year,Cast,Hotstar,Netflix,Movies
0,9.5,kannada-2026,"[Yash, Kiara Advani]",0,0,Toxic
1,9.5,hindi-2025,"[Ranbeer Singh, Sara]",1,1,Durandhar
2,10.0,english-2019,"[RDJ, Scarlett Johnson, Steve Rogers]",1,0,Avengers: Endgame
3,8.0,hindi-2024,"[Sharukhan, Deepika Padukone]",0,1,Jawan
4,NaN,telugu-2020,"[Allu Arjun, Pooja Hegde]",0,1,Alavaikuntapuram
5,9.0,english-2016,"[Wade Wilson, Juli]",1,0,Marvel: Deadpool
6,9.0,tElugu-2018,"[Prabhas, Tamanna]",0,1,Bahubali
7,10.0,english-2024,"[Tom Holland, Zendaya]",0,1,Spider-Man No Way Home
8,10.0,KAnnada-2020,"[Yash, Srinidhi Shetty]",0,1,K.G.F: 2
9,NaN,EnGlish-2022,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange

In [227]:
df['Language-year']=df['Language-year'].str.title()

In [228]:
df

,Rating,Language-year,Cast,Hotstar,Netflix,Movies
0,9.5,Kannada-2026,"[Yash, Kiara Advani]",0,0,Toxic
1,9.5,Hindi-2025,"[Ranbeer Singh, Sara]",1,1,Durandhar
2,10.0,English-2019,"[RDJ, Scarlett Johnson, Steve Rogers]",1,0,Avengers: Endgame
3,8.0,Hindi-2024,"[Sharukhan, Deepika Padukone]",0,1,Jawan
4,NaN,Telugu-2020,"[Allu Arjun, Pooja Hegde]",0,1,Alavaikuntapuram
5,9.0,English-2016,"[Wade Wilson, Juli]",1,0,Marvel: Deadpool
6,9.0,Telugu-2018,"[Prabhas, Tamanna]",0,1,Bahubali
7,10.0,English-2024,"[Tom Holland, Zendaya]",0,1,Spider-Man No Way Home
8,10.0,Kannada-2020,"[Yash, Srinidhi Shetty]",0,1,K.G.F: 2
9,NaN,English-2022,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange

In [229]:
df[['Language','Year']]=df['Language-year'].str.split('-',expand=True)

In [230]:
df

,Rating,Language-year,Cast,Hotstar,Netflix,Movies,Language,Year
0,9.5,Kannada-2026,"[Yash, Kiara Advani]",0,0,Toxic,Kannada,2026
1,9.5,Hindi-2025,"[Ranbeer Singh, Sara]",1,1,Durandhar,Hindi,2025
2,10.0,English-2019,"[RDJ, Scarlett Johnson, Steve Rogers]",1,0,Avengers: Endgame,English,2019
3,8.0,Hindi-2024,"[Sharukhan, Deepika Padukone]",0,1,Jawan,Hindi,2024
4,NaN,Telugu-2020,"[Allu Arjun, Pooja Hegde]",0,1,Alavaikuntapuram,Telugu,2020
5,9.0,English-2016,"[Wade Wilson, Juli]",1,0,Marvel: Deadpool,English,2016
6,9.0,Telugu-2018,"[Prabhas, Tamanna]",0,1,Bahubali,Telugu,2018
7,10.0,English-2024,"[Tom Holland, Zendaya]",0,1,Spider-Man No Way Home,English,2024
8,10.0,Kannada-2020,"[Yash, Srinidhi Shetty]",0,1,K.G.F: 2,Kannada,2020
9,NaN,English-2022,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange,English,2022

In [231]:
df=df.drop(columns=['Language-year'])

In [232]:
df

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
0,9.5,"[Yash, Kiara Advani]",0,0,Toxic,Kannada,2026
1,9.5,"[Ranbeer Singh, Sara]",1,1,Durandhar,Hindi,2025
2,10.0,"[RDJ, Scarlett Johnson, Steve Rogers]",1,0,Avengers: Endgame,English,2019
3,8.0,"[Sharukhan, Deepika Padukone]",0,1,Jawan,Hindi,2024
4,NaN,"[Allu Arjun, Pooja Hegde]",0,1,Alavaikuntapuram,Telugu,2020
5,9.0,"[Wade Wilson, Juli]",1,0,Marvel: Deadpool,English,2016
6,9.0,"[Prabhas, Tamanna]",0,1,Bahubali,Telugu,2018
7,10.0,"[Tom Holland, Zendaya]",0,1,Spider-Man No Way Home,English,2024
8,10.0,"[Yash, Srinidhi Shetty]",0,1,K.G.F: 2,Kannada,2020
9,NaN,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange,English,2022

In [233]:
df[df['Language']=='Kannada']

   Rating                     Cast  Hotstar  Netflix    Movies Language  Year
0     9.5     [Yash, Kiara Advani]        0        0     Toxic  Kannada  2026
8    10.0  [Yash, Srinidhi Shetty]        0        1  K.G.F: 2  Kannada  2020

In [234]:
df[df['Language']=='Hindi']

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
1,9.5,"[Ranbeer Singh, Sara]",1,1,Durandhar,Hindi,2025
3,8.0,"[Sharukhan, Deepika Padukone]",0,1,Jawan,Hindi,2024

In [235]:
df[df['Language']=='English']

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
2,10.0,"[RDJ, Scarlett Johnson, Steve Rogers]",1,0,Avengers: Endgame,English,2019
5,9.0,"[Wade Wilson, Juli]",1,0,Marvel: Deadpool,English,2016
7,10.0,"[Tom Holland, Zendaya]",0,1,Spider-Man No Way Home,English,2024
9,NaN,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange,English,2022

In [236]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rating    8 non-null      float64
 1   Cast      10 non-null     object
 2   Hotstar   10 non-null     int64
 3   Netflix   10 non-null     int64
 4   Movies    10 non-null     object
 5   Language  10 non-null     object
 6   Year      10 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 688.0+ bytes

## astype( )

astype( ) is used to convert from one data type to another data type.

In [237]:
df=df.astype({'Year':'int'})

In [238]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rating    8 non-null      float64
 1   Cast      10 non-null     object
 2   Hotstar   10 non-null     int64
 3   Netflix   10 non-null     int64
 4   Movies    10 non-null     object
 5   Language  10 non-null     object
 6   Year      10 non-null     int32
dtypes: float64(1), int32(1), int64(2), object(3)
memory usage: 648.0+ bytes

### loc[ ]    

- loc[row_based, [column_based]]

- loc[condition, [col_name/list of movies]]

- loc[(Parameter 1) & (Parameter 2)]

In [239]:
df.loc[5]
df.loc[9]

Rating                                   NaN
Cast        [Benedict Cumberbatch, Cristine]
Hotstar                                    1
Netflix                                    0
Movies                Marvel: Doctor Strange
Language                             English
Year                                    2022
Name: 9, dtype: object

In [240]:
df.loc[1,['Movies','Rating']]

Movies    Durandhar
Rating          9.5
Name: 1, dtype: object

In [241]:
df.loc[[0,3,5]]

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
0,9.5,"[Yash, Kiara Advani]",0,0,Toxic,Kannada,2026
3,8.0,"[Sharukhan, Deepika Padukone]",0,1,Jawan,Hindi,2024
5,9.0,"[Wade Wilson, Juli]",1,0,Marvel: Deadpool,English,2016

In [242]:
df.loc[[0,3,5],['Movies','Rating']]

             Movies  Rating
0             Toxic     9.5
3             Jawan     8.0
5  Marvel: Deadpool     9.0

In [243]:
df

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
0,9.5,"[Yash, Kiara Advani]",0,0,Toxic,Kannada,2026
1,9.5,"[Ranbeer Singh, Sara]",1,1,Durandhar,Hindi,2025
2,10.0,"[RDJ, Scarlett Johnson, Steve Rogers]",1,0,Avengers: Endgame,English,2019
3,8.0,"[Sharukhan, Deepika Padukone]",0,1,Jawan,Hindi,2024
4,NaN,"[Allu Arjun, Pooja Hegde]",0,1,Alavaikuntapuram,Telugu,2020
5,9.0,"[Wade Wilson, Juli]",1,0,Marvel: Deadpool,English,2016
6,9.0,"[Prabhas, Tamanna]",0,1,Bahubali,Telugu,2018
7,10.0,"[Tom Holland, Zendaya]",0,1,Spider-Man No Way Home,English,2024
8,10.0,"[Yash, Srinidhi Shetty]",0,1,K.G.F: 2,Kannada,2020
9,NaN,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange,English,2022

In [244]:
df[(df['Language']=='Kannada') & (df['Netflix']==1)]

   Rating                     Cast  Hotstar  Netflix    Movies Language  Year
8    10.0  [Yash, Srinidhi Shetty]        0        1  K.G.F: 2  Kannada  2020

- When i have to print the condition and column both together then i have go with the .loc[ ] method.

In [245]:
df.loc[(df['Language']=='Kannada') & (df['Netflix']==1)]

   Rating                     Cast  Hotstar  Netflix    Movies Language  Year
8    10.0  [Yash, Srinidhi Shetty]        0        1  K.G.F: 2  Kannada  2020

In [246]:
df.loc[(df['Year']==2018) | (df['Year']==2022)]

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
6,9.0,"[Prabhas, Tamanna]",0,1,Bahubali,Telugu,2018
9,NaN,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange,English,2022

In [247]:
df.loc[((df['Year']==2018) | (df['Year']==2022)) & (df['Hotstar']==1)]

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
9,NaN,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange,English,2022

- NaN -> Not a Number

- Null values or missing values

In [248]:
df=df.fillna(7)
df

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
0,9.5,"[Yash, Kiara Advani]",0,0,Toxic,Kannada,2026
1,9.5,"[Ranbeer Singh, Sara]",1,1,Durandhar,Hindi,2025
2,10.0,"[RDJ, Scarlett Johnson, Steve Rogers]",1,0,Avengers: Endgame,English,2019
3,8.0,"[Sharukhan, Deepika Padukone]",0,1,Jawan,Hindi,2024
4,7.0,"[Allu Arjun, Pooja Hegde]",0,1,Alavaikuntapuram,Telugu,2020
5,9.0,"[Wade Wilson, Juli]",1,0,Marvel: Deadpool,English,2016
6,9.0,"[Prabhas, Tamanna]",0,1,Bahubali,Telugu,2018
7,10.0,"[Tom Holland, Zendaya]",0,1,Spider-Man No Way Home,English,2024
8,10.0,"[Yash, Srinidhi Shetty]",0,1,K.G.F: 2,Kannada,2020
9,7.0,"[Benedict Cumberbatch, Cristine]",1,0,Marvel: Doctor Strange,English,2022

- Convert to .csv file ->      df.to_csv('name.csv',index=False) (always go with .csv) 

- Convert to .xlsx file ->    df.to_excel('name.xlsx') (not much prefered because it will sometimes change the format )

- index=False will remove the index values from the file which we are converting

In [249]:
df.to_csv('m1.csv',index=False)

In [250]:
df.to_excel('m2.xlsx',index=False)

In [251]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rating    10 non-null     float64
 1   Cast      10 non-null     object
 2   Hotstar   10 non-null     int64
 3   Netflix   10 non-null     int64
 4   Movies    10 non-null     object
 5   Language  10 non-null     object
 6   Year      10 non-null     int32
dtypes: float64(1), int32(1), int64(2), object(3)
memory usage: 648.0+ bytes

In [252]:
df=df.astype({'Cast':'str'})
# df['Cast']=df['Cast'].astype(str)

In [253]:
df['Cast']=df['Cast'].str.strip('[]')

In [254]:
df['Cast']=df['Cast'].str.replace(', ', '-')

In [255]:
df['Cast']=df['Cast'].str.replace("'", " ")

In [256]:
df['Cast']

0                       Yash - Kiara Advani
1                      Ranbeer Singh - Sara
2     RDJ - Scarlett Johnson - Steve Rogers
3              Sharukhan - Deepika Padukone
4                  Allu Arjun - Pooja Hegde
5                        Wade Wilson - Juli
6                         Prabhas - Tamanna
7                     Tom Holland - Zendaya
8                    Yash - Srinidhi Shetty
9           Benedict Cumberbatch - Cristine
Name: Cast, dtype: object

In [257]:
df

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year
0,9.5,Yash - Kiara Advani,0,0,Toxic,Kannada,2026
1,9.5,Ranbeer Singh - Sara,1,1,Durandhar,Hindi,2025
2,10.0,RDJ - Scarlett Johnson - Steve Rogers,1,0,Avengers: Endgame,English,2019
3,8.0,Sharukhan - Deepika Padukone,0,1,Jawan,Hindi,2024
4,7.0,Allu Arjun - Pooja Hegde,0,1,Alavaikuntapuram,Telugu,2020
5,9.0,Wade Wilson - Juli,1,0,Marvel: Deadpool,English,2016
6,9.0,Prabhas - Tamanna,0,1,Bahubali,Telugu,2018
7,10.0,Tom Holland - Zendaya,0,1,Spider-Man No Way Home,English,2024
8,10.0,Yash - Srinidhi Shetty,0,1,K.G.F: 2,Kannada,2020
9,7.0,Benedict Cumberbatch - Cristine,1,0,Marvel: Doctor Strange,English,2022

## melt( ) function - it will convert columns into rows

- when we want to apply aggregate functions or group by clause or when we want to visualize or 

when we need it for machine learning process we need to convert it into to rows.

#### Syntax
pd.melt(DataFrame, id_vaiables, value_variables, variable_names, value_names)

- id_vars (id_variables) = Columns doesn't want to change.

- value_vars (value_variables) = Columns which we want to convert into the rows.

- var_name (vaiable_names) = name used to give to column which we are converting (column name for old columns).

- value_name (value_names) = name for the value columns

In [258]:
pd.melt(df,value_vars=['Hotstar','Netflix'])

   variable  value
0   Hotstar      0
1   Hotstar      1
2   Hotstar      1
3   Hotstar      0
4   Hotstar      0
5   Hotstar      1
6   Hotstar      0
7   Hotstar      0
8   Hotstar      0
9   Hotstar      1
10  Netflix      0
11  Netflix      1
12  Netflix      0
13  Netflix      1
14  Netflix      1
15  Netflix      0
16  Netflix      1
17  Netflix      1
18  Netflix      1
19  Netflix      0

In [259]:
pd.melt(df,value_vars=['Hotstar','Netflix'],var_name='OTT',value_name='Available')

        OTT  Available
0   Hotstar          0
1   Hotstar          1
2   Hotstar          1
3   Hotstar          0
4   Hotstar          0
5   Hotstar          1
6   Hotstar          0
7   Hotstar          0
8   Hotstar          0
9   Hotstar          1
10  Netflix          0
11  Netflix          1
12  Netflix          0
13  Netflix          1
14  Netflix          1
15  Netflix          0
16  Netflix          1
17  Netflix          1
18  Netflix          1
19  Netflix          0

In [260]:
df1=pd.melt(df,id_vars=['Movies','Rating'],value_vars=['Hotstar','Netflix'],var_name='OTT',value_name='Available')

In [261]:
df1

                    Movies  Rating      OTT  Available
0                    Toxic     9.5  Hotstar          0
1                Durandhar     9.5  Hotstar          1
2        Avengers: Endgame    10.0  Hotstar          1
3                    Jawan     8.0  Hotstar          0
4         Alavaikuntapuram     7.0  Hotstar          0
5         Marvel: Deadpool     9.0  Hotstar          1
6                 Bahubali     9.0  Hotstar          0
7   Spider-Man No Way Home    10.0  Hotstar          0
8                 K.G.F: 2    10.0  Hotstar          0
9   Marvel: Doctor Strange     7.0  Hotstar          1
10                   Toxic     9.5  Netflix          0
11               Durandhar     9.5  Netflix          1
12       Avengers: Endgame    10.0  Netflix          0
13                   Jawan     8.0  Netflix          1
14        Alavaikuntapuram     7.0  Netflix          1
15        Marvel: Deadpool     9.0  Netflix          0
16                Bahubali     9.0  Netflix          1
17  Spider-Man No Way Home    10.0  Netflix          1
18                K.G.F: 2    10.0  Netflix          1
19  Marvel: Doctor Strange     7.0  Netflix          0

In [262]:
df1=df1.loc[df1['Available']==1]

In [263]:
df1

                    Movies  Rating      OTT  Available
1                Durandhar     9.5  Hotstar          1
2        Avengers: Endgame    10.0  Hotstar          1
5         Marvel: Deadpool     9.0  Hotstar          1
9   Marvel: Doctor Strange     7.0  Hotstar          1
11               Durandhar     9.5  Netflix          1
13                   Jawan     8.0  Netflix          1
14        Alavaikuntapuram     7.0  Netflix          1
16                Bahubali     9.0  Netflix          1
17  Spider-Man No Way Home    10.0  Netflix          1
18                K.G.F: 2    10.0  Netflix          1

In [264]:
df1=df1.drop(columns=['Available'])

## reset_index( )

- reset_index(drop=True) method is used to reset the index values and drop=True removes the old index values

In [265]:
df1=df1.reset_index(drop=True)

In [266]:
df1

                   Movies  Rating      OTT
0               Durandhar     9.5  Hotstar
1       Avengers: Endgame    10.0  Hotstar
2        Marvel: Deadpool     9.0  Hotstar
3  Marvel: Doctor Strange     7.0  Hotstar
4               Durandhar     9.5  Netflix
5                   Jawan     8.0  Netflix
6        Alavaikuntapuram     7.0  Netflix
7                Bahubali     9.0  Netflix
8  Spider-Man No Way Home    10.0  Netflix
9                K.G.F: 2    10.0  Netflix

In [267]:
df['Total_platforms']=df['Hotstar']+df['Netflix']

In [268]:
df

,Rating,Cast,Hotstar,Netflix,Movies,Language,Year,Total_platforms
0,9.5,Yash - Kiara Advani,0,0,Toxic,Kannada,2026,0
1,9.5,Ranbeer Singh - Sara,1,1,Durandhar,Hindi,2025,2
2,10.0,RDJ - Scarlett Johnson - Steve Rogers,1,0,Avengers: Endgame,English,2019,1
3,8.0,Sharukhan - Deepika Padukone,0,1,Jawan,Hindi,2024,1
4,7.0,Allu Arjun - Pooja Hegde,0,1,Alavaikuntapuram,Telugu,2020,1
5,9.0,Wade Wilson - Juli,1,0,Marvel: Deadpool,English,2016,1
6,9.0,Prabhas - Tamanna,0,1,Bahubali,Telugu,2018,1
7,10.0,Tom Holland - Zendaya,0,1,Spider-Man No Way Home,English,2024,1
8,10.0,Yash - Srinidhi Shetty,0,1,K.G.F: 2,Kannada,2020,1
9,7.0,Benedict Cumberbatch - Cristine,1,0,Marvel: Doctor Strange,English,2022,1

## Aggregate Functions in Pandas

- SUM( )
- MEAN( )
- MIN( )
- COUNT( )
- MAX ( )

In [269]:
df1

                   Movies  Rating      OTT
0               Durandhar     9.5  Hotstar
1       Avengers: Endgame    10.0  Hotstar
2        Marvel: Deadpool     9.0  Hotstar
3  Marvel: Doctor Strange     7.0  Hotstar
4               Durandhar     9.5  Netflix
5                   Jawan     8.0  Netflix
6        Alavaikuntapuram     7.0  Netflix
7                Bahubali     9.0  Netflix
8  Spider-Man No Way Home    10.0  Netflix
9                K.G.F: 2    10.0  Netflix

In [270]:
df1['Rating'].count()

10

In [271]:
df['Rating'].agg(['min','max','mean','count'])

min       7.0
max      10.0
mean      8.9
count    10.0
Name: Rating, dtype: float64

In [272]:
df.agg({'Rating':'min', 'Movies':'count'})

Rating     7.0
Movies    10.0
dtype: float64

In [273]:
df.agg({'Rating':['min','max','mean'], 'Movies':'count'})

       Rating  Movies
min       7.0     NaN
max      10.0     NaN
mean      8.9     NaN
count     NaN    10.0

# Group By

In [274]:
df1.groupby('OTT')

- We are just grouping the records we are not performing any aggregate fucntions so its just returning the object.

In [275]:
df1.groupby('OTT').agg({'Rating':'mean'})

           Rating
OTT
Hotstar  8.875000
Netflix  8.916667

In [276]:
df1.groupby('OTT').agg({'Rating':['min','mean'],'Movies':'count'})

        Rating           Movies
           min      mean  count
OTT
Hotstar    7.0  8.875000      4
Netflix    7.0  8.916667      6